# Generated by Django 2.2.1 on 2020-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bengalske',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('rok', models.IntegerField(default=0)),
                ('hmotnost', models.IntegerField()),
                ('vyska', models.IntegerField()),
                ('kastracie', models.IntegerField()),
                ('popis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='britske',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('rok', models.IntegerField(default=0)),
                ('hmotnost', models.IntegerField()),
                ('vyska', models.IntegerField()),
                ('kastracie', models.IntegerField()),
                ('popis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='perszske',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('rok', models.IntegerField(default=0)),
                ('hmotnost', models.IntegerField()),
                ('vyska', models.IntegerField()),
                ('kastracie', models.IntegerField()),
                ('popis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ragdoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('rok', models.IntegerField(default=0)),
                ('hmotnost', models.IntegerField()),
                ('vyska', models.IntegerField()),
                ('kastracie', models.IntegerField()),
                ('popis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='savanove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('rok', models.IntegerField(default=0)),
                ('hmotnost', models.IntegerField()),
                ('vyska', models.IntegerField()),
                ('kastracie', models.IntegerField()),
                ('popis', models.TextField()),
            ],
        ),
    ]
