# Generated by Django 2.2.1 on 2020-03-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bengalske',
            name='kastracie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='britske',
            name='kastracie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perszske',
            name='kastracie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ragdoll',
            name='kastracie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='savanove',
            name='kastracie',
            field=models.CharField(max_length=50),
        ),
    ]
