# Generated by Django 2.1.2 on 2020-03-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macky', '0002_auto_20200303_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='bengalske',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='britske',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='perszske',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ragdoll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='savanove',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
