# Generated by Django 2.2.1 on 2020-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macky', '0003_auto_20200304_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_cats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasa', models.CharField(max_length=50)),
                ('meno', models.CharField(max_length=50)),
                ('rok', models.IntegerField(default=0)),
                ('hmotnost', models.IntegerField()),
                ('vyska', models.IntegerField()),
                ('kastracie', models.CharField(max_length=50)),
                ('popis', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
