# Generated by Django 2.2.1 on 2020-03-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macky', '0004_all_cats'),
    ]

    operations = [
        migrations.CreateModel(
            name='macka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=50)),
                ('rok', models.IntegerField(default=0)),
                ('hmotnost', models.IntegerField()),
                ('vyska', models.IntegerField()),
                ('kastracie', models.CharField(max_length=50)),
                ('popis', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno_rasy', models.CharField(max_length=100)),
                ('popis_rasy', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='all_cats',
        ),
        migrations.DeleteModel(
            name='bengalske',
        ),
        migrations.DeleteModel(
            name='britske',
        ),
        migrations.DeleteModel(
            name='perszske',
        ),
        migrations.DeleteModel(
            name='ragdoll',
        ),
        migrations.DeleteModel(
            name='savanove',
        ),
        migrations.AddField(
            model_name='macka',
            name='typ_rasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macky.rasa'),
        ),
    ]
