# Generated by Django 2.2.1 on 2020-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macky', '0005_auto_20200330_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macka',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='macka',
            name='width_field',
        ),
        migrations.AddField(
            model_name='rasa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
